def analyze_sentiment(text):
    positive_words = {
        # ── INGLESE ──
        "good": 1, "great": 2, "excellent": 2, "amazing": 2, "awesome": 2,
        "fantastic": 2, "wonderful": 2, "brilliant": 2, "superb": 2, "outstanding": 2,
        "perfect": 2, "beautiful": 1, "love": 2, "loved": 2, "loving": 1,
        "happy": 1, "happiness": 2, "joy": 2, "joyful": 2, "excited": 1,
        "exciting": 1, "impressive": 1, "incredible": 2, "magnificent": 2,
        "positive": 1, "best": 2, "better": 1, "nice": 1, "enjoy": 1,
        "enjoyed": 1, "enjoying": 1, "fun": 1, "funny": 1, "like": 1,
        "liked": 1, "useful": 1, "helpful": 1, "recommend": 1, "recommended": 1,
        "innovative": 1, "successful": 1, "success": 1, "win": 1, "winner": 1,
        "winning": 1, "safe": 1, "strong": 1, "powerful": 1, "hope": 1,
        "hopeful": 1, "promising": 1, "progress": 1, "improvement": 1, "improved": 1,
        "easy": 1, "efficient": 1, "smart": 1, "clever": 1, "genius": 2,
        "grateful": 2, "thankful": 1, "blessed": 2, "thrilled": 2, "delighted": 2,
        "pleased": 1, "satisfied": 1, "satisfaction": 1, "proud": 1, "pride": 1,
        "accomplish": 1, "accomplished": 2, "achievement": 2, "achieve": 1,
        "reward": 1, "rewarding": 2, "celebrate": 1, "celebration": 1,
        "enthusiastic": 2, "enthusiasm": 2, "passionate": 1,
        "passion": 1, "inspiring": 2, "inspired": 2, "inspiration": 2,
        "creative": 1, "creativity": 1, "innovation": 2,
        "opportunity": 1, "opportunities": 1, "growth": 1, "growing": 1,
        "flourish": 2, "flourishing": 2, "thrive": 2, "thriving": 2,
        "peaceful": 1, "peace": 1, "calm": 1, "relaxing": 1, "comfortable": 1,
        "comfort": 1, "freedom": 1, "free": 1, "independent": 1, "independence": 1,
        "healthy": 1, "health": 1, "fit": 1, "wellness": 1, "wellbeing": 1,
        "friendly": 1, "kind": 1, "kindness": 2, "generous": 1, "generosity": 1,
        "caring": 1, "supportive": 1, "support": 1, "together": 1, "unity": 1,
        "united": 1, "cooperative": 1, "cooperation": 1, "teamwork": 1,
        "fair": 1, "justice": 1, "honest": 1, "honesty": 1, "trust": 1,
        "trustworthy": 2, "reliable": 1, "responsible": 1, "dedicated": 1,
        "commitment": 1, "committed": 1, "motivated": 1, "motivation": 1,
        "energetic": 1, "energy": 1, "dynamic": 1, "vibrant": 1, "lively": 1,
        "warm": 1, "charming": 1, "attractive": 1, "elegant": 1, "graceful": 1,
        "noble": 1, "brave": 1, "courage": 2, "courageous": 2, "bold": 1,
        "confident": 1, "confidence": 1, "optimistic": 1, "optimism": 2,
        "cheerful": 1, "bright": 1, "radiant": 1, "glowing": 1, "sparkling": 1,
        "miracle": 2, "magical": 2, "extraordinary": 2, "exceptional": 2,
        "remarkable": 2, "special": 1, "unique": 1, "genuine": 1, "authentic": 1,
        "valuable": 1, "worthy": 1, "meaningful": 1, "significant": 1,
        "revolutionary": 2, "transformative": 2, "breakthrough": 2, "pioneering": 2,
        "leading": 1, "leader": 1, "expert": 1, "professional": 1, "skilled": 1,
        "talented": 1, "gifted": 1, "capable": 1, "competent": 1, "qualified": 1,
        "educated": 1, "knowledgeable": 1, "wise": 1, "wisdom": 2, "insightful": 1,
        "productive": 1, "effective": 1, "organized": 1,
        "consistent": 1, "stable": 1, "solid": 1, "firm": 1, "steady": 1,
        "improve": 1, "improving": 1, "enhance": 1, "enhanced": 1, "boost": 1,
        "boosted": 1, "advance": 1, "advanced": 1, "upgrade": 1, "upgraded": 1,
        "recover": 1, "recovered": 1, "recovery": 1, "heal": 1, "healed": 1,
        "save": 1, "saved": 1, "protect": 1, "protected": 1, "secure": 1,
        "security": 1, "solution": 1, "solve": 1, "solved": 1, "fix": 1, "fixed": 1,
        "clean": 1, "clear": 1, "pure": 1, "fresh": 1, "new": 1, "renewed": 1,
        "restored": 1, "revived": 1, "reborn": 2, "transformed": 1,
        "empowered": 2, "empowerment": 2, "liberated": 2, "liberation": 2,

        # ── ITALIANO ──
        "bello": 1, "bella": 1, "belli": 1, "belle": 1,
        "ottimo": 2, "ottima": 2, "ottimi": 2, "ottime": 2,
        "fantastico": 2, "fantastica": 2, "fantastici": 2, "fantastiche": 2,
        "meraviglioso": 2, "meravigliosa": 2, "meravigliosi": 2, "meravigliose": 2,
        "eccellente": 2, "eccellenti": 2,
        "perfetto": 2, "perfetta": 2, "perfetti": 2, "perfette": 2,
        "buono": 1, "buona": 1, "buoni": 1, "buone": 1,
        "bravo": 1, "brava": 1, "bravi": 1, "brave": 1,
        "amore": 2, "amato": 2, "amata": 2, "amare": 1,
        "felice": 1, "felici": 1, "felicità": 2,
        "gioia": 2, "gioioso": 1, "gioiosa": 1, "gioiosi": 1, "gioiose": 1,
        "positivo": 1, "positiva": 1, "positivi": 1,
        "migliore": 2, "migliori": 2, "meglio": 1,
        "piacevole": 1, "piacevoli": 1, "piacere": 1,
        "divertente": 1, "divertenti": 1, "divertimento": 1,
        "utile": 1, "utili": 1, "utilità": 1,
        "consiglio": 1, "consigliato": 1, "consigliata": 1,
        "innovativo": 1, "innovativa": 1, "innovativi": 1, "innovazione": 2,
        "successo": 1, "vincere": 1, "vittoria": 2, "vincitore": 1, "vincitrice": 1,
        "forte": 1, "forti": 1, "potente": 1, "potenti": 1,
        "speranza": 1, "speranzoso": 1, "speranzosa": 1,
        "promettente": 1, "promettenti": 1,
        "progresso": 1, "progressi": 1,
        "miglioramento": 1, "miglioramenti": 1, "migliorato": 1, "migliorata": 1,
        "facile": 1, "facili": 1, "semplicità": 1,
        "efficiente": 1, "efficienti": 1, "efficienza": 1,
        "intelligente": 1, "intelligenti": 1, "intelligenza": 1,
        "geniale": 2, "geniali": 2, "genio": 2,
        "straordinario": 2, "straordinaria": 2, "straordinari": 2, "straordinarie": 2,
        "incredibile": 2, "incredibili": 2,
        "stupendo": 2, "stupenda": 2, "stupendi": 2, "stupende": 2,
        "magnifico": 2, "magnifica": 2, "magnifici": 2, "magnifiche": 2,
        "splendido": 2, "splendida": 2, "splendidi": 2, "splendide": 2,
        "orgoglioso": 1, "orgogliosa": 1, "orgogliosi": 1, "orgogliose": 1, "orgoglio": 1,
        "soddisfatto": 1, "soddisfatta": 1, "soddisfatti": 1, "soddisfatte": 1, "soddisfazione": 1,
        "entusiasta": 2, "entusiasti": 2, "entusiasmo": 2,
        "appassionato": 1, "appassionata": 1, "appassionati": 1, "passione": 1,
        "ispirato": 2, "ispirata": 2, "ispirazione": 2, "ispirante": 2,
        "creativo": 1, "creativa": 1, "creativi": 1, "creatività": 1,
        "opportunità": 1, "crescita": 1, "crescere": 1,
        "pacifico": 1, "pacifica": 1, "pace": 1,
        "tranquillo": 1, "tranquilla": 1, "tranquilli": 1, "tranquille": 1,
        "sereno": 1, "serena": 1, "sereni": 1, "serene": 1, "serenità": 1,
        "libero": 1, "libera": 1, "liberi": 1, "libere": 1, "libertà": 1,
        "sano": 1, "sana": 1, "sani": 1, "sane": 1, "salute": 1, "benessere": 1,
        "gentile": 1, "gentili": 1, "gentilezza": 2,
        "generoso": 1, "generosa": 1, "generosi": 1, "generose": 1, "generosità": 1,
        "solidale": 1, "solidali": 1, "solidarietà": 1,
        "unito": 1, "unita": 1, "uniti": 1, "unite": 1, "unione": 1, "unità": 1,
        "giusto": 1, "giusta": 1, "giusti": 1, "giuste": 1, "giustizia": 1,
        "onesto": 1, "onesta": 1, "onesti": 1, "oneste": 1, "onestà": 1,
        "coraggioso": 2, "coraggiosa": 2, "coraggiosi": 2, "coraggio": 2,
        "fiducioso": 1, "fiduciosa": 1, "fiducia": 1,
        "ottimista": 1, "ottimisti": 1, "ottimismo": 2,
        "allegro": 1, "allegra": 1, "allegri": 1, "allegre": 1, "allegria": 1,
        "luminoso": 1, "luminosa": 1, "luminosi": 1, "luminose": 1,
        "miracoloso": 2, "miracolosa": 2, "miracolo": 2,
        "magico": 2, "magica": 2, "magici": 2, "magiche": 2, "magia": 2,
        "speciale": 1, "speciali": 1,
        "prezioso": 1, "preziosa": 1, "preziosi": 1, "preziose": 1,
        "significativo": 1, "significativa": 1, "significativi": 1, "significative": 1,
        "rivoluzionario": 2, "rivoluzionaria": 2, "rivoluzione": 2,
        "esperto": 1, "esperta": 1, "esperti": 1, "esperte": 1, "esperienza": 1,
        "talentuoso": 1, "talentuosa": 1, "talentuosi": 1, "talentuose": 1,
        "capace": 1, "capaci": 1,
        "produttivo": 1, "produttiva": 1, "produttivi": 1, "produttive": 1,
        "efficace": 1, "efficaci": 1,
        "stabile": 1, "stabili": 1, "stabilità": 1,
        "migliorare": 1, "potenziare": 1, "avanzare": 1,
        "guarire": 1, "guarito": 1, "guarita": 1, "guarigione": 1,
        "salvare": 1, "salvato": 1, "salvata": 1,
        "proteggere": 1, "protetto": 1, "protetta": 1, "protezione": 1,
        "sicuro": 1, "sicura": 1, "sicuri": 1, "sicure": 1, "sicurezza": 1,
        "soluzione": 1, "soluzioni": 1, "risolvere": 1, "risolto": 1, "risolta": 1,
        "pulito": 1, "pulita": 1, "puliti": 1, "pulite": 1,
        "fresco": 1, "fresca": 1, "freschi": 1, "fresche": 1,
        "nuovo": 1, "nuova": 1, "nuovi": 1, "nuove": 1,
        "rinnovato": 1, "rinnovata": 1, "rinnovati": 1, "rinnovate": 1,
        "emozionante": 2, "emozionanti": 2, "emozione": 1,
        "benissimo": 2, "benone": 2, "bravissimo": 2, "bravissima": 2,
    }

    negative_words = {
        # ── INGLESE ──
        "bad": -1, "terrible": -2, "horrible": -2, "awful": -2, "disgusting": -2,
        "worst": -2, "worse": -1, "poor": -1, "disappointing": -2, "disappointed": -1,
        "hate": -2, "hated": -2, "hating": -1, "ugly": -1, "boring": -1,
        "useless": -2, "broken": -1, "fail": -2, "failed": -2, "failure": -2,
        "sad": -1, "sadness": -1, "unhappy": -1, "miserable": -2, "depressed": -2,
        "depression": -2, "angry": -1, "anger": -1, "furious": -2, "frustrated": -1,
        "frustrating": -1, "annoying": -1, "annoyed": -1, "dangerous": -2,
        "damage": -1, "damaged": -1, "corrupt": -2, "corrupted": -2, "evil": -2,
        "wrong": -1, "error": -1, "problem": -1, "issue": -1, "difficult": -1,
        "impossible": -2, "weak": -1, "stupid": -2, "idiot": -2,
        "waste": -1, "wasted": -1, "lie": -2, "lied": -2, "fake": -2,
        "scam": -2, "fraud": -2, "toxic": -2, "violent": -2, "violence": -2,
        "crisis": -2, "disaster": -2, "catastrophe": -2,
        "dreadful": -2, "appalling": -2, "atrocious": -2,
        "pathetic": -2, "ridiculous": -1, "absurd": -1, "nonsense": -1,
        "dumb": -2, "ignorant": -1, "incompetent": -2,
        "dishonest": -2, "deceptive": -2, "manipulative": -2,
        "abusive": -2, "abuse": -2, "harassment": -2, "bully": -2, "bullying": -2,
        "threaten": -2, "threat": -2, "intimidate": -2, "intimidation": -2,
        "fear": -1, "scared": -1, "terrified": -2, "panic": -2, "anxiety": -1,
        "anxious": -1, "stress": -1, "stressed": -1, "overwhelmed": -1,
        "exhausted": -1, "tired": -1, "burnout": -2,
        "lonely": -1, "loneliness": -2, "isolated": -1, "abandoned": -2,
        "rejected": -2, "betrayed": -2, "betrayal": -2,
        "unfair": -1, "unjust": -2, "inequality": -1, "discrimination": -2,
        "racist": -2, "racism": -2, "sexist": -2, "sexism": -2,
        "poverty": -2, "homeless": -1, "hungry": -1, "starving": -2,
        "sick": -1, "ill": -1, "disease": -2, "death": -2, "dead": -2, "die": -2,
        "dying": -2, "killed": -2, "murder": -2, "crime": -2, "criminal": -2,
        "illegal": -1, "banned": -1, "censored": -1,
        "destroyed": -2, "ruined": -2,
        "collapsed": -2, "bankrupt": -2, "debt": -1, "loss": -1, "losing": -1,
        "lost": -1, "decline": -1, "declining": -1, "falling": -1, "crashed": -2,
        "crash": -2, "collapse": -2, "recession": -2, "inflation": -1,
        "unemployment": -2, "layoff": -2, "fired": -1,
        "pollution": -2, "contamination": -2, "poison": -2,
        "war": -2, "conflict": -1, "attack": -2, "bomb": -2, "weapon": -1,
        "suffer": -2, "suffering": -2, "pain": -2, "hurt": -1, "injury": -1,
        "wounded": -1, "trauma": -2, "tragedy": -2, "tragic": -2,
        "shame": -1, "shameful": -2, "embarrassing": -1, "embarrassed": -1,
        "regret": -1, "regretful": -1, "guilty": -1, "guilt": -1,
        "worthless": -2, "meaningless": -1, "pointless": -1, "hopeless": -2,
        "desperate": -2, "despair": -2, "misery": -2,
        "controversy": -1, "controversial": -1, "scandal": -2, "outrage": -2,
        "outrageous": -2, "unacceptable": -2, "inexcusable": -2,

        # ── ITALIANO ──
        "brutto": -1, "brutta": -1, "brutti": -1, "brutte": -1,
        "pessimo": -2, "pessima": -2, "pessimi": -2, "pessime": -2,
        "terribile": -2, "terribili": -2,
        "orribile": -2, "orribili": -2,
        "schifoso": -2, "schifosa": -2, "schifosi": -2, "schifose": -2, "schifo": -2,
        "peggiore": -2, "peggiori": -2, "peggio": -1,
        "deludente": -2, "deludenti": -2,
        "deluso": -1, "delusa": -1, "delusi": -1, "deluse": -1, "delusione": -2,
        "odio": -2, "odioso": -2, "odiosa": -2, "odiosi": -2, "odiose": -2,
        "noioso": -1, "noiosa": -1, "noiosi": -1, "noiose": -1, "noia": -1,
        "inutile": -2, "inutili": -2,
        "rotto": -1, "rotta": -1, "rotti": -1, "rotte": -1,
        "fallire": -2, "fallito": -2, "fallita": -2, "fallimento": -2,
        "triste": -1, "tristi": -1, "tristezza": -1,
        "infelice": -1, "infelici": -1,
        "misero": -2, "misera": -2, "miseri": -2, "misere": -2, "miseria": -2,
        "depresso": -2, "depressa": -2, "depressi": -2, "depresse": -2, "depressione": -2,
        "arrabbiato": -1, "arrabbiata": -1, "arrabbiati": -1, "arrabbiate": -1, "rabbia": -1,
        "furioso": -2, "furiosa": -2, "furiosi": -2, "furiose": -2,
        "frustrato": -1, "frustrata": -1, "frustrati": -1, "frustrate": -1, "frustrazione": -1,
        "fastidioso": -1, "fastidiosa": -1, "fastidiosi": -1, "fastidiose": -1, "fastidio": -1,
        "pericoloso": -2, "pericolosa": -2, "pericolosi": -2, "pericolose": -2, "pericolo": -2,
        "danno": -1, "danni": -1, "danneggiato": -1, "danneggiata": -1,
        "corrotto": -2, "corrotta": -2, "corrotti": -2, "corrotte": -2, "corruzione": -2,
        "sbagliato": -1, "sbagliata": -1, "sbagliati": -1, "sbagliate": -1,
        "errore": -1, "errori": -1,
        "problema": -1, "problemi": -1,
        "difficile": -1, "difficili": -1, "difficoltà": -1,
        "impossibile": -2, "impossibili": -2,
        "debole": -1, "deboli": -1, "debolezza": -1,
        "stupido": -2, "stupida": -2, "stupidi": -2, "stupide": -2, "stupidità": -2,
        "idiota": -2, "idioti": -2,
        "spreco": -1, "sprechi": -1, "sprecato": -1, "sprecata": -1,
        "bugiardo": -2, "bugiarda": -2, "bugiardi": -2, "bugiarde": -2,
        "menzogna": -2, "menzogne": -2, "bugia": -2, "bugie": -2,
        "falso": -2, "falsa": -2, "falsi": -2, "false": -2,
        "truffa": -2, "truffe": -2, "truffatore": -2,
        "tossico": -2, "tossica": -2, "tossici": -2, "tossiche": -2,
        "violento": -2, "violenta": -2, "violenti": -2, "violente": -2, "violenza": -2,
        "crisi": -2, "disastro": -2, "disastri": -2,
        "catastrofe": -2, "catastrofi": -2,
        "guerra": -2, "conflitto": -1, "conflitti": -1, "attacco": -2, "attacchi": -2,
        "paura": -1, "paure": -1, "spaventato": -1, "spaventata": -1,
        "terrore": -2, "terrorismo": -2, "terrorista": -2,
        "ansia": -1, "ansioso": -1, "ansiosa": -1, "ansiosi": -1, "ansiose": -1,
        "stress": -1, "stressato": -1, "stressata": -1,
        "stanco": -1, "stanca": -1, "stanchi": -1, "stanche": -1, "stanchezza": -1,
        "solo": -1, "sola": -1, "solitudine": -2,
        "abbandonato": -2, "abbandonata": -2, "abbandono": -2,
        "tradito": -2, "tradita": -2, "tradimento": -2,
        "ingiusto": -1, "ingiusta": -1, "ingiusti": -1, "ingiuste": -1, "ingiustizia": -2,
        "discriminazione": -2,
        "povertà": -2, "povero": -1, "povera": -1, "poveri": -1, "povere": -1,
        "malato": -1, "malata": -1, "malati": -1, "malate": -1, "malattia": -2,
        "morte": -2, "morto": -2, "morta": -2, "morti": -2, "morire": -2,
        "omicidio": -2, "crimine": -2, "criminale": -2, "criminali": -2,
        "illegale": -1, "illegali": -1,
        "distrutto": -2, "distrutta": -2, "distrutti": -2, "distrutte": -2, "distruzione": -2,
        "rovinato": -2, "rovinata": -2, "rovina": -2,
        "collasso": -2, "bancarotta": -2, "debito": -1, "debiti": -1,
        "perdita": -1, "perdite": -1, "perdere": -1, "perso": -1, "persa": -1,
        "declino": -1, "decadenza": -2, "crollo": -2,
        "recessione": -2, "inflazione": -1, "disoccupazione": -2,
        "inquinamento": -2, "contaminazione": -2, "veleno": -2,
        "sofferenza": -2, "soffrire": -2, "dolore": -2, "ferito": -1, "ferita": -1,
        "trauma": -2, "tragedia": -2, "tragico": -2, "tragica": -2,
        "vergogna": -1, "vergognoso": -2, "vergognosa": -2,
        "imbarazzante": -1, "imbarazzato": -1, "imbarazzata": -1,
        "rimpianto": -1, "rimpianti": -1, "pentito": -1, "pentita": -1,
        "colpa": -1, "colpevole": -1, "colpevoli": -1,
        "disperato": -2, "disperata": -2, "disperati": -2, "disperate": -2, "disperazione": -2,
        "scandalo": -2, "scandali": -2, "oltraggio": -2,
        "inaccettabile": -2, "imperdonabile": -2,
        "pessimismo": -2, "pessimista": -1,
        "ripugnante": -2, "disgustoso": -2, "disgustosa": -2,
        "orrendo": -2, "orrenda": -2,
        "malissimo": -2, "maluccio": -1, "male": -1,
    }

    intensifiers = {
        "very": 1.5, "really": 1.5, "extremely": 2.0, "absolutely": 2.0,
        "incredibly": 2.0, "so": 1.3, "quite": 1.2, "totally": 1.5,
        "completely": 1.5, "utterly": 2.0, "highly": 1.5, "super": 1.5,
        "deeply": 1.5, "truly": 1.5, "genuinely": 1.3, "remarkably": 1.5,
        "exceptionally": 2.0, "especially": 1.3, "particularly": 1.3,
        "molto": 1.5, "davvero": 1.5, "estremamente": 2.0, "assolutamente": 2.0,
        "incredibilmente": 2.0, "così": 1.3, "abbastanza": 1.2, "totalmente": 1.5,
        "completamente": 1.5, "altamente": 1.5, "profondamente": 1.5,
        "veramente": 1.5, "proprio": 1.3, "particolarmente": 1.3,
        "decisamente": 1.5, "certamente": 1.3, "sicuramente": 1.3,
        "tremendamente": 2.0, "enormemente": 2.0, "immensamente": 2.0,
    }

    negations = {
        "not", "no", "never", "neither", "nor", "without", "hardly", "barely",
        "non", "mai", "né", "senza", "appena", "nessuno", "niente", "nulla",
    }

    if not text or text.strip() == "":
        return "Neutro"

    words = text.lower().split()
    score = 0.0
    i = 0

    while i < len(words):
        word = words[i].strip(".,!?;:\"'()[]{}")

        if word in positive_words or word in negative_words:
            word_score = positive_words.get(word, 0) + negative_words.get(word, 0)

            multiplier = 1.0
            if i > 0:
                prev = words[i - 1].strip(".,!?;:\"'()[]{}")
                if prev in intensifiers:
                    multiplier = intensifiers[prev]
                elif prev in negations:
                    multiplier = -1.0
            if i > 1:
                prev2 = words[i - 2].strip(".,!?;:\"'()[]{}")
                if prev2 in negations and words[i - 1].strip(".,!?;:\"'()[]{}") not in positive_words and words[i - 1].strip(".,!?;:\"'()[]{}") not in negative_words:
                    multiplier = -1.0

            score += word_score * multiplier

        i += 1

    if score > 0.3:
        return "Positivo"
    elif score < -0.3:
        return "Negativo"
    else:
        return "Neutro"